# Site settings
title: PyData Eindhoven
description:
  PYDATA EINDHOVEN BRINGS TOGETHER<br />
  USERS AND DEVELOPERS OF OPEN-SOURCE<br />
  SOFTWARE IN THE SCIENTIFIC COMPUTING<br />
  AND PYTHON ECOSYSTEM.

#<a href="https://numfocus.org/blog/pydata-covid-19-response">NumFOCUS guidance for PyData events regarding COVID-19</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eindhoven.pydata.org" # the base hostname & protocol for your site


future: true

tickets_url: #https://www.eventbrite.com/e/pydata-eindhoven-2020-tickets-117358340957
schedule_url: #https://pydata.org/eindhoven2020/schedule/
cfp_url:
meetup_url: https://www.meetup.com/en-AU/PyData-Eindhoven/events/276147716/

dates:
location:

greeting:
  title: About PyData
  text:
    PyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States.
    PyData provides a forum for the international community of users and developers of data analysis tools to
    share ideas and learn from each other.<br /><br />

    The global PyData network promotes discussion of best practices, new approaches,
    and emerging technologies for data management, processing, analytics, and visualization.
    PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R.<br /><br />

    The PyData Code of Conduct governs this conference. To discuss any issues or concerns relating to the code of
    conduct or the behavior of anyone at a PyData conference (or meetup), please contact NumFOCUS Executive Director 
    Leah Silen (+1 512-222-5449; leah@numfocus.org ) or the local organisers at eindhoven@pydata.org.

social:
  twitter: https://twitter.com/PyDataEindhoven
  github: https://github.com/PyDataEindhoven

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

include: ['_pages']

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/PyDataEindhoven
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/PydataEindhoven

# Build settings
markdown: kramdown

destination: ./build

plugins:
  - jekyll-sitemap
